### ISSUE TITLE
Добавить шрифт DejaVu Sans 

### ISSUE THREAD

**Issue by MaximObrubov** [MaximObrubov/rulatex#1]
шрифт должен быть по умолчанию в библиотеке
webpack можежет загружать пути, но за счет того, что в output есть вложенность, то пути ломаются

возможно нужен другой лоадер

**Comment by aarefiev** [comment]
done

надо будет проверить на iOS, проблема была именно из-за подключения svg шрифта в отдельном src, для разработки текущего состава достаточно
